#############################################################################
# Makefile for building: stitchy
# Generated by qmake (2.01a) (Qt 4.8.3) on: Tue Nov 20 11:05:56 2012
# Project:  stitchy.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile stitchy.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lqjson -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = canvas.cpp \
		cell.cpp \
		color.cpp \
		colormanager.cpp \
		document.cpp \
		editor.cpp \
		editoractions.cpp \
		globalstate.cpp \
		mainwindow.cpp \
		palettemodel.cpp \
		palettewidget.cpp \
		settings.cpp \
		sparsemap.cpp \
		stitch.cpp \
		utils.cpp \
		main.cpp moc_canvas.cpp \
		moc_colormanager.cpp \
		moc_document.cpp \
		moc_editor.cpp \
		moc_globalstate.cpp \
		moc_mainwindow.cpp \
		moc_palettewidget.cpp \
		qrc_stitchy.cpp
OBJECTS       = canvas.o \
		cell.o \
		color.o \
		colormanager.o \
		document.o \
		editor.o \
		editoractions.o \
		globalstate.o \
		mainwindow.o \
		palettemodel.o \
		palettewidget.o \
		settings.o \
		sparsemap.o \
		stitch.o \
		utils.o \
		main.o \
		moc_canvas.o \
		moc_colormanager.o \
		moc_document.o \
		moc_editor.o \
		moc_globalstate.o \
		moc_mainwindow.o \
		moc_palettewidget.o \
		qrc_stitchy.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		stitchy.pro
QMAKE_TARGET  = stitchy
DESTDIR       = 
TARGET        = stitchy

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: stitchy.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile stitchy.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile stitchy.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/stitchy1.0.0 || $(MKDIR) .tmp/stitchy1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/stitchy1.0.0/ && $(COPY_FILE) --parents canvas.h cell.h color.h colormanager.h common.h document.h editor.h editoractions.h globalstate.h mainwindow.h palettemodel.h palettewidget.h settings.h sparsemap.h stitch.h utils.h .tmp/stitchy1.0.0/ && $(COPY_FILE) --parents stitchy.qrc .tmp/stitchy1.0.0/ && $(COPY_FILE) --parents canvas.cpp cell.cpp color.cpp colormanager.cpp document.cpp editor.cpp editoractions.cpp globalstate.cpp mainwindow.cpp palettemodel.cpp palettewidget.cpp settings.cpp sparsemap.cpp stitch.cpp utils.cpp main.cpp .tmp/stitchy1.0.0/ && (cd `dirname .tmp/stitchy1.0.0` && $(TAR) stitchy1.0.0.tar stitchy1.0.0 && $(COMPRESS) stitchy1.0.0.tar) && $(MOVE) `dirname .tmp/stitchy1.0.0`/stitchy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/stitchy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_canvas.cpp moc_colormanager.cpp moc_document.cpp moc_editor.cpp moc_globalstate.cpp moc_mainwindow.cpp moc_palettewidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_canvas.cpp moc_colormanager.cpp moc_document.cpp moc_editor.cpp moc_globalstate.cpp moc_mainwindow.cpp moc_palettewidget.cpp
moc_canvas.cpp: cell.h \
		stitch.h \
		canvas.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) canvas.h -o moc_canvas.cpp

moc_colormanager.cpp: color.h \
		common.h \
		colormanager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) colormanager.h -o moc_colormanager.cpp

moc_document.cpp: color.h \
		common.h \
		document.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) document.h -o moc_document.cpp

moc_editor.cpp: editor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editor.h -o moc_editor.cpp

moc_globalstate.cpp: editor.h \
		stitch.h \
		globalstate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) globalstate.h -o moc_globalstate.cpp

moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_palettewidget.cpp: palettewidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) palettewidget.h -o moc_palettewidget.cpp

compiler_rcc_make_all: qrc_stitchy.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_stitchy.cpp
qrc_stitchy.cpp: stitchy.qrc \
		res/colors.json
	/usr/bin/rcc -name stitchy stitchy.qrc -o qrc_stitchy.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

canvas.o: canvas.cpp cell.h \
		stitch.h \
		document.h \
		color.h \
		common.h \
		editor.h \
		editoractions.h \
		globalstate.h \
		sparsemap.h \
		canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvas.o canvas.cpp

cell.o: cell.cpp document.h \
		color.h \
		common.h \
		stitch.h \
		utils.h \
		cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o cell.cpp

color.o: color.cpp stitch.h \
		color.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o color.o color.cpp

colormanager.o: colormanager.cpp colormanager.h \
		color.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colormanager.o colormanager.cpp

document.o: document.cpp cell.h \
		stitch.h \
		color.h \
		common.h \
		editor.h \
		globalstate.h \
		sparsemap.h \
		utils.h \
		document.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o document.o document.cpp

editor.o: editor.cpp document.h \
		color.h \
		common.h \
		editoractions.h \
		editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o editor.cpp

editoractions.o: editoractions.cpp cell.h \
		stitch.h \
		document.h \
		color.h \
		common.h \
		sparsemap.h \
		editoractions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editoractions.o editoractions.cpp

globalstate.o: globalstate.cpp globalstate.h \
		editor.h \
		stitch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globalstate.o globalstate.cpp

mainwindow.o: mainwindow.cpp canvas.h \
		cell.h \
		stitch.h \
		color.h \
		common.h \
		document.h \
		globalstate.h \
		editor.h \
		palettewidget.h \
		settings.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

palettemodel.o: palettemodel.cpp color.h \
		common.h \
		palettemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o palettemodel.o palettemodel.cpp

palettewidget.o: palettewidget.cpp color.h \
		common.h \
		globalstate.h \
		editor.h \
		stitch.h \
		palettemodel.h \
		palettewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o palettewidget.o palettewidget.cpp

settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

sparsemap.o: sparsemap.cpp cell.h \
		stitch.h \
		document.h \
		color.h \
		common.h \
		sparsemap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sparsemap.o sparsemap.cpp

stitch.o: stitch.cpp color.h \
		common.h \
		document.h \
		globalstate.h \
		editor.h \
		stitch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stitch.o stitch.cpp

utils.o: utils.cpp utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_canvas.o: moc_canvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvas.o moc_canvas.cpp

moc_colormanager.o: moc_colormanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_colormanager.o moc_colormanager.cpp

moc_document.o: moc_document.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_document.o moc_document.cpp

moc_editor.o: moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editor.o moc_editor.cpp

moc_globalstate.o: moc_globalstate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_globalstate.o moc_globalstate.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_palettewidget.o: moc_palettewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_palettewidget.o moc_palettewidget.cpp

qrc_stitchy.o: qrc_stitchy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_stitchy.o qrc_stitchy.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

